#!/usr/bin/env bash
# Configuring domain zone
function get_dns_record {
  domain=$1
  subdomain=$2

  if [[ -z "$subdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi

  for sub in "${subdomains[@]}"
  do
    record=$(dig "$sub"."$domain" | awk '$4=="A" {print $1}')
    destination=$(dig "$sub"."$domain" | awk '$4=="A" {print $5}')
    echo "The subdomain $sub is a $record record and points to $destination"
  done
}

get_dns_record "$1" "$2"
