#!/usr/bin/env bash
# Define a function to display information about a subdomain
display_info() {
    # Execute the dig command to get DNS information for the subdomain
    result=$(dig "$1"."$2" +short)

    # Extract the IP address and record type using awk
    ip=$(echo "$result" | awk '{print $1}')
    record_type=$(echo "$result" | awk '{print $2}')

    # Print the extracted information
    echo "The subdomain $1 is a $record_type record and points to $ip"
}

# If only domain argument is provided, display information for default subdomains
if [ $# -eq 1 ]; then
    display_info www "$1"
    display_info lb-01 "$1"
    display_info web-01 "$1"
    display_info web-02 "$1"
# If both domain and subdomain arguments are provided, display information for the specified subdomain
elif [ $# -eq 2 ]; then
    display_info "$2" "$1"
fi
