#!/usr/bin/env bash
# Check if number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extracting arguments
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer file using scp, disabling strict host key checking
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/

# Check if scp command executed successfully
if [ $? -eq 0 ]; then
    echo "File transferred successfully to $username@$server_ip:~/"
else
    echo "Error occurred while transferring file"
fi
