#!/usr/bin/env bash
# Configures a server to listening on port 80 on all IPs
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill "$(pgrep nginx | head -n 1)"
